### ISSUE TITLE
QT wallet does not run on Ubuntu 16

### ISSUE THREAD

**Issue by juanpastas** [dzimbeck/BitBay#3] opened 2017-01-29 05:14 UTC
I installed libboost-system-dev, and libdb5.3++.

libboost version 1.58 was installed.

But I keep getting error:

```
error while loading shared libraries: libboost_system.so.1.55.0: cannot open shared object file: No such file or directory
```

I downloaded qt wallet from bitbay.market

# Update

```
sudo apt-get -y install build-essential libssl-dev libdb++-dev libboost-all-dev libqrencode-dev libminiupnpc-dev || force "apt-get install failed"
```

Installed more deps. But error is still the same.

# Update 2

I tried with the download from the site, the tar.gz. And I got:

```
./BitBay.sh 
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Cannot mix incompatible Qt library (version 0x40807) with this library (version 0x40802)
Aborted (core dumped)
```

**Comment by dzimbeck** [comment] 2017-01-29 07:36
Well Linux binaries are harder to make than windows binaries due to the many different platforms of Linux. For the markets wallet for example some people add the 32 bit architecture and run that build. 

So your error with the markets wallet, which is actually Halo Python source that tarball has two packages both 32 and 64 bit (The markets wallet has two Linux binaries). Try running the 32 bit and adding the Linux 32 bit architecture package support: https://www.unixmen.com/enable-32-bit-support-64-bit-ubuntu-13-10-greater/

So as for the QT binary which has been tested on only 64 bit Linux Jessie, you might want to check to see if you are running 32 bit or 64 bit. I've confirmed that there are some libraries not found on my Linux wheezy that are on jessie.

So first try 32 bit package following the method of adding and updating 32 bit arch packages.

If none of that works you can build bitbayd from source by using any of the scripts here on the github. There is a Linux32 and Linux64 sh file script for building with commands so it would be the correct package from this github followed by a reset and build command:
./linuxBitBay.sh --reset --build

Then bitbayd will be built exactly for your system and you can just replace the one in the tarball package with a binary that better suits your version of Linux.

I don't think this issue you raised has anything to do with the source code though. So I will wait for your response before I close it. If you need more help with this come to the BitBay slack and any of us would be happy to help you.

**Closed** 2017-02-09 06:16 UTC

**Comment by DrSluice** [comment] 2017-04-23 14:58
as of April 23 2017 the tar.gz packages of the market client are still not sane. Constant error messages that the file is not actually in gz format. Followed the above tutorial and have confirmed 32bit support on my 64 bit Linux box. Where are the Linux sourcecode files to even begin sorting out what is missing here? I will try to help if only I could find the Linux sourcecode files for download. Everything on the Bitbay Website is essentially deprecated, wonky, or just plain broken. I would like to try the 32 bit version, if only I knew where to get it. Thanks.

**Comment by dzimbeck** [comment] 2017-04-23 16:21
Hi did you read the above comment? The source code is here: 
http://www.davtonia.com/bithalo/haloobf.zip

The website is fine nothing is broken there although I'm looking for someone to update it. Also this is not the place to discuss the site, this is the github for reporting issues. You can certainly talk to me on Slack if you like to walk you through setup.

The dependency issue about mixing incompatible QT libraries mentioned by the first gentlemen was fixed by including qt.conf in the package as that bug is well know for other applications as well. 

The Bitbay.market website has the markets wallet and has both 32 and 64 bit Linux versions. Let me know more specifically what errors you get if any.

Thanks
